### ISSUE TITLE
I want to join your slack team!

### ISSUE THREAD

**Issue by goranche** [cocoaheads-slovenija/learner-project#1]
We have a slack team (CocoaHeads Slovenia) where we discuss our meetups, talks, iOS development in general, and of course, these projects as well.
If you'd like to join that team, please comment on this issue with the email you'd like to use for slack access, and we might invite you 😉

**Comment by markoengelman** [comment]
I would like to join 😁 Please send invitation to: engelman.marko@gmail.com thank you 😉

**Comment by majkl8** [comment]
Would like to join - mihbov@gmail.com. Thanks. Lp Miha

**Comment by alesp56** [comment]
Me too! clubbydj@gmail.com. Hvala.
